version: '3.7'

networks:
  app-tier:
    driver: bridge

services:
  orchestrator:
    image: kyle83567/orchestrator
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - fragment-1
      - fragment-2
      - fragment-3
  fragment-1:
    image: kyle83567/frontend-fragment-1
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
  fragment-2:
    image: kyle83567/frontend-fragment-2
    ports:
      - "8060:8060"
    environment:
      - PORT=8060
  fragment-3:
    image: kyle83567/frontend-fragment-3
    ports:
      - "8070:8070"
    environment:
      - PORT=8070
