apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: body
  name: body
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: body
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        io.kompose.service: body
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: kyle83567/body:v15
        imagePullPolicy: ""
        name: body
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
