apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
data:
  services: "header,body,footer"
  markup: "<div>Here is Fragment 1 {{header}}</div><div>Here is Fragment 2 {{body}}</div><div>Here is Fragment 3 {{footer}}</div>"
