apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: FRONTEND_SERVICES
          valueFrom:
            configMapKeyRef:
              name: orchestrator-config
              key: services
        - name: FRONTEND_MARKUP
          valueFrom:
            configMapKeyRef:
              name: orchestrator-config
              key: markup

        image: kyle83567/orchestrator:v8
        imagePullPolicy: ""
        name: orchestrator
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
